# Generated by Django 5.0.2 on 2024-03-22 01:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gutenberg', '0001_initial'), ('gutenberg', '0002_chunk_text'), ('gutenberg', '0003_entropy'), ('gutenberg', '0004_remove_chunk_rel_i_chunk_last_modified'), ('gutenberg', '0005_delete_entropy'), ('gutenberg', '0006_entropy'), ('gutenberg', '0007_entropy_jensen_shannon')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_builder_id', models.IntegerField(unique=True)),
                ('vocab_counts', models.JSONField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='gutenberg.book')),
                ('text', models.TextField(default='')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Entropy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_vocab_counts', models.JSONField()),
                ('shared_vocab_ratio', models.FloatField()),
                ('shared_vocab_count', models.IntegerField()),
                ('entr_gained', models.FloatField()),
                ('entr_lost', models.FloatField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entropies', to='gutenberg.chunk')),
                ('related_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutenberg.chunk')),
                ('jensen_shannon', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('chunk', 'related_chunk')},
            },
        ),
    ]
