# Generated by Django 5.0.2 on 2024-03-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
