# Generated by Django 5.0.2 on 2024-03-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0002_chunk_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entropy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_vocab_count', models.IntegerField()),
                ('combined_vocab_count', models.IntegerField()),
                ('rel_entr', models.FloatField()),
                ('rel_entr_normed', models.FloatField()),
                ('shared_count_x_rel_entr', models.FloatField()),
                ('shared_count_x_rel_entr_normed', models.FloatField()),
                ('combined_count_x_rel_entr', models.FloatField()),
                ('combined_count_x_rel_entr_normed', models.FloatField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entropies', to='gutenberg.chunk')),
                ('related_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gutenberg.chunk')),
            ],
            options={
                'unique_together': {('chunk', 'related_chunk')},
            },
        ),
    ]
