# Generated by Django 5.0.2 on 2024-03-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0001_squashed_0007_entropy_jensen_shannon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entropy',
            name='jensen_shannon',
            field=models.FloatField(),
        ),
    ]
