# Generated by Django 5.0.2 on 2024-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0008_alter_chunk_last_modified_alter_chunk_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
